### ISSUE TITLE
style transform

### ISSUE THREAD

**Issue by guoqian0097282** [mnicnc404/CartoonGan-tensorflow#12]
Hi, I use your method to train the data. I got the result.

![image](https://user-images.githubusercontent.com/8876075/58444808-5ec4a300-812c-11e9-9c82-4805988f8076.png)

But I want get images like this.
![image](https://user-images.githubusercontent.com/8876075/58444867-acd9a680-812c-11e9-95f9-b3e20fa3f495.png)

This is my training data, I have trained 100 times.

Can you tell me why?

**Comment by leemengtaiwan** [comment]
Hi, thanks for trying out our code and the cute image!

In order to achieve what you want, it would be better if you try some other GANs which can generate images from scratch (e.g, from a random distribution). 

In CartoonGAN (and our implementation), the goal is to make some small changes to make the image "cartoon-like", rather than transform the images dramatically.

**Comment by guoqian0097282** [comment]
OK,thank you!!

**Comment by 360disrupt** [comment]
I think that one: https://github.com/junyanz/CycleGAN or this one might be for you: https://github.com/lengstrom/fast-style-transfer
