### ISSUE TITLE
OOM error with just 1 1080p .png using the pre-trained in colab

### ISSUE THREAD

**Issue by lorrp1** [mnicnc404/CartoonGan-tensorflow#32]
Hello, im trying to convert 1 1080p pic <2mb

using this: 

!python cartoonize.py --styles hayao --batch_size 1 --skip_comparison --input_dir /content/prova --output_dir /content/CartOUT --keep_original_size

but i get this error:

tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,270,480,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Conv2D]

which i have read is related to the lack of enough gpu ram, is there a way to get over it without increase gpu ram? im using batch_size = 1 and colab

ram in colab: 

Gen RAM Free: 12.6 GB  | Proc size: 415.4 MB
GPU RAM Free: 7611MB | Used: 0MB | Util   0% | Total 7611MB

without --keep_original_size it works fine.

any idea?

**Comment by mnicnc404** [comment]
Apparently 1080p is too memory-consuming for our model and colab GPU. If you really want to keep the original size, try GPU with more memory like P100, V100, which you can find at GCP or Azure, etc. We cannot guarantee that you can successfully transfer 1080p image on P100 or V100 since we do not own a P100 or G100 vm.
