### ISSUE TITLE
[environment] cudatoolkit cudnn and python3.6

### ISSUE THREAD

**Issue by Zachary4biz** [mnicnc404/CartoonGan-tensorflow#33]
I have found something might be useful while preparing the environment (conda)

my environment: gcc4.8.5 centos7.5.1804

change `python=3.7.3` to `python=3.6.8` in environment_linux_gpu.yml and remove all `=py37...`
- with python3.7, there might be an error of glibc as `libm.so.6: version `GLIBC_2.23' not found` if working on some ancient machine.

`conda install cudatoolkit=10.0` & `conda install cudnn=7.6.0`
- get `libcublas.so.10.0 not found` when `import tensorflow`

edit line7 of `keras_contrib/utils/test_utils.py` if come across syntax error of this line.
- mostly some error of spacing

**Comment by mnicnc404** [comment]
Compatibility between tensorflow and cuda / cudnn has always been an issue. We have to apologize for not providing cuda / cudnn installing instructions. We've also noticed that there are some compatibility issues of ancient nvidia gpus, drivers and cuda. Currently we don't have time to handle gpu / cuda / cudnn compatibility issues since we contribute to this repo in our spare time.

Thank you again for your information.
